config/routes.rb
Rails.application.routes.draw do
  resources :bank_accounts

  resources :users

  resources :funds

  resources :fund_cashes

  resources :fund_categorizations

  resources :fund_managements

  resources :fund_managers

  resources :fund_stores

  resources :fund_transactions

  resources :fundstore_categories

  resources :holdings

  resources :stocks

  resources :user_accounts

  resources :user_holdings

  resources :user_transactions

end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
  belongs_to :user
end

app/models/fund.rb
class Fund < ActiveRecord::Base
  belongs_to :user_account
  belongs_to :fund_manager
  has_many :stocks
  has_many :fundstore_categories
  has_many :fund_managers
  has_many :user_transactions
  has_many :user_accounts
  has_many :fund_managements
  has_many :fund_transactions
  has_many :holdings
  has_many :user_holdings
  has_one :fund_cash
end

app/models/fund_cash.rb
class FundCash < ActiveRecord::Base
  belongs_to :fund
end

app/models/fund_management.rb
class FundManagement < ActiveRecord::Base
  belongs_to :fund_manager
  belongs_to :fund
end

app/models/fund_manager.rb
class FundManager < ActiveRecord::Base
  has_many :fund_managements
  has_many :funds
  validates_formatting_of :manager_email, using: :email
end

app/models/fund_store.rb
class FundStore < ActiveRecord::Base
end

app/models/fund_transaction.rb
class FundTransaction < ActiveRecord::Base
  belongs_to :stock
  belongs_to :fund
end

app/models/fundstore_category.rb
class FundstoreCategory < ActiveRecord::Base
  belongs_to :fund_store
  belongs_to :fund
  has_many :fund_categorizations
  has_many :funds
end

app/models/holding.rb
class Holding < ActiveRecord::Base
  belongs_to :stock
  belongs_to :fund
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :fund
  has_many :fund_transactions
  has_many :funds
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bank_accounts
  has_many :user_accounts
  validates_formatting_of :email, using: :email
end

app/models/user_account.rb
class UserAccount < ActiveRecord::Base
  belongs_to :user
  belongs_to :fund
  has_many :user_transactions
  has_many :funds
  has_many :user_holdings
end

app/models/user_holding.rb
class UserHolding < ActiveRecord::Base
  belongs_to :user_account
  belongs_to :fund
end

app/models/user_transaction.rb
class UserTransaction < ActiveRecord::Base
  belongs_to :user_account
  belongs_to :fund
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :set_bank_account, only: [:show, :edit, :update, :destroy]

  # GET /bank_accounts
  # GET /bank_accounts.json
  def index
    @bank_accounts = BankAccount.all
  end

  # GET /bank_accounts/1
  # GET /bank_accounts/1.json
  def show
  end

  # GET /bank_accounts/new
  def new
    @bank_account = BankAccount.new
  end

  # GET /bank_accounts/1/edit
  def edit
  end

  # POST /bank_accounts
  # POST /bank_accounts.json
  def create
    @bank_account = BankAccount.new(bank_account_params)

    respond_to do |format|
      if @bank_account.save
        format.html { redirect_to @bank_account, notice: 'Bank account was successfully created.' }
        format.json { render :show, status: :created, location: @bank_account }
      else
        format.html { render :new }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_accounts/1
  # PATCH/PUT /bank_accounts/1.json
  def update
    respond_to do |format|
      if @bank_account.update(bank_account_params)
        format.html { redirect_to @bank_account, notice: 'Bank account was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank_account }
      else
        format.html { render :edit }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_accounts/1
  # DELETE /bank_accounts/1.json
  def destroy
    @bank_account.destroy
    respond_to do |format|
      format.html { redirect_to bank_accounts_url, notice: 'Bank account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_account
      @bank_account = BankAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_account_params
      params.require(:bank_account).permit(:bank_account_number, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/helpers/fund_cashes_helper.rb
module FundCashesHelper
end

app/helpers/fund_stores_helper.rb
module FundStoresHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/holdings_helper.rb
module HoldingsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bank_accounts/_form.html.erb
<%= form_for @bank_account, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :bank_account_number, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :bank_account_number, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  bank_accounts_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/bank_accounts/edit.html.erb
<%- model_class = BankAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => BankAccount %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bank_accounts/index.html.erb
<%- model_class = BankAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => BankAccount %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:bank_account_number) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bank_accounts.each do |bank_account| %>
      <tr>
        <td><%= bank_account.id %></td>
        <td><%= bank_account.bank_account_number %></td>
        <td><%=l bank_account.created_at, format: :long %></td>
        <td>
          <%= link_to bank_account_path(bank_account), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to bank_account_path(bank_account), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bank_account_path,
            :class => 'btn btn-primary' %>

app/views/bank_accounts/new.html.erb
<%- model_class = BankAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => BankAccount %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bank_accounts/show.html.erb
<%- model_class = BankAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => BankAccount %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:bank_account_number) %></dt>
      <dd><pre class="prettyprint"><%= @bank_account.bank_account_number %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bank_accounts_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bank_account_path(@bank_account), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bank_account_path(@bank_account),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>