config/routes.rb
Rails.application.routes.draw do
  resources :bank_accounts

  resources :users

  resources :funds

  resources :fund_cashes

  resources :fund_categorizations

  resources :fund_managements

  resources :fund_managers

  resources :fund_stores

  resources :fund_transactions

  resources :fundstore_categories

  resources :holdings

  resources :stocks

  resources :user_accounts

  resources :user_holdings

  resources :user_transactions

end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
  belongs_to :user
end

app/models/fund.rb
class Fund < ActiveRecord::Base
  belongs_to :user_account
  belongs_to :fund_manager
  has_many :stocks
  has_many :fundstore_categories
  has_many :fund_managers
  has_many :user_transactions
  has_many :user_accounts
  has_many :fund_managements
  has_many :fund_transactions
  has_many :holdings
  has_many :user_holdings
  has_one :fund_cash
end

app/models/fund_cash.rb
class FundCash < ActiveRecord::Base
  belongs_to :fund
end

app/models/fund_categorization.rb
class FundCategorization < ActiveRecord::Base
  belongs_to :fundstore_category
  belongs_to :fund
end

app/models/fund_management.rb
class FundManagement < ActiveRecord::Base
  belongs_to :fund_manager
  belongs_to :fund
end

app/models/fund_manager.rb
class FundManager < ActiveRecord::Base
  has_many :fund_managements
  has_many :funds
  validates_formatting_of :manager_email, using: :email
end

app/models/fund_store.rb
class FundStore < ActiveRecord::Base
end

app/models/fund_transaction.rb
class FundTransaction < ActiveRecord::Base
  belongs_to :stock
  belongs_to :fund
end

app/models/fundstore_category.rb
class FundstoreCategory < ActiveRecord::Base
  belongs_to :fund_store
  belongs_to :fund
  has_many :fund_categorizations
  has_many :funds
end

app/models/holding.rb
class Holding < ActiveRecord::Base
  belongs_to :stock
  belongs_to :fund
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :fund
  has_many :fund_transactions
  has_many :funds
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bank_accounts
  has_many :user_accounts
  validates_formatting_of :email, using: :email
end

app/models/user_account.rb
class UserAccount < ActiveRecord::Base
  belongs_to :user
  belongs_to :fund
  has_many :user_transactions
  has_many :funds
  has_many :user_holdings
end

app/models/user_holding.rb
class UserHolding < ActiveRecord::Base
  belongs_to :user_account
  belongs_to :fund
end

app/models/user_transaction.rb
class UserTransaction < ActiveRecord::Base
  belongs_to :user_account
  belongs_to :fund
end

app/controllers/fund_categorizations_controller.rb
class FundCategorizationsController < ApplicationController
  before_action :set_fund_categorization, only: [:show, :edit, :update, :destroy]

  # GET /fund_categorizations
  # GET /fund_categorizations.json
  def index
    @fund_categorizations = FundCategorization.all
  end

  # GET /fund_categorizations/1
  # GET /fund_categorizations/1.json
  def show
  end

  # GET /fund_categorizations/new
  def new
    @fund_categorization = FundCategorization.new
  end

  # GET /fund_categorizations/1/edit
  def edit
  end

  # POST /fund_categorizations
  # POST /fund_categorizations.json
  def create
    @fund_categorization = FundCategorization.new(fund_categorization_params)

    respond_to do |format|
      if @fund_categorization.save
        format.html { redirect_to @fund_categorization, notice: 'Fund categorization was successfully created.' }
        format.json { render :show, status: :created, location: @fund_categorization }
      else
        format.html { render :new }
        format.json { render json: @fund_categorization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fund_categorizations/1
  # PATCH/PUT /fund_categorizations/1.json
  def update
    respond_to do |format|
      if @fund_categorization.update(fund_categorization_params)
        format.html { redirect_to @fund_categorization, notice: 'Fund categorization was successfully updated.' }
        format.json { render :show, status: :ok, location: @fund_categorization }
      else
        format.html { render :edit }
        format.json { render json: @fund_categorization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fund_categorizations/1
  # DELETE /fund_categorizations/1.json
  def destroy
    @fund_categorization.destroy
    respond_to do |format|
      format.html { redirect_to fund_categorizations_url, notice: 'Fund categorization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fund_categorization
      @fund_categorization = FundCategorization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fund_categorization_params
      params.require(:fund_categorization).permit(:fundstore_category_id, :fund_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fund_cashes_helper.rb
module FundCashesHelper
end

app/helpers/fund_categorizations_helper.rb
module FundCategorizationsHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/holdings_helper.rb
module HoldingsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fund_categorizations/_form.html.erb
<%= form_for @fund_categorization, :html => { :class => 'form-horizontal form-model' } do |f| %>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  fund_categorizations_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/fund_categorizations/edit.html.erb
<%- model_class = FundCategorization -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => FundCategorization %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fund_categorizations/index.html.erb
<%- model_class = FundCategorization -%>
<div class="page-header">
  <h1><%=t '.title', :default => FundCategorization %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @fund_categorizations.each do |fund_categorization| %>
      <tr>
        <td><%= fund_categorization.id %></td>
        <td><%=l fund_categorization.created_at, format: :long %></td>
        <td>
          <%= link_to fund_categorization_path(fund_categorization), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to fund_categorization_path(fund_categorization), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_fund_categorization_path,
            :class => 'btn btn-primary' %>

app/views/fund_categorizations/new.html.erb
<%- model_class = FundCategorization -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => FundCategorization %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fund_categorizations/show.html.erb
<%- model_class = FundCategorization -%>
<div class="page-header">
  <h1><%=t '.title', :default => FundCategorization %></h1>
</div>

<div class="fieldset">
  <dl>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              fund_categorizations_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_fund_categorization_path(@fund_categorization), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              fund_categorization_path(@fund_categorization),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>