config/routes.rb
Rails.application.routes.draw do
  resources :bank_accounts

  resources :users

  resources :funds

  resources :fund_cashes

  resources :fund_categorizations

  resources :fund_managements

  resources :fund_managers

  resources :fund_stores

  resources :fund_transactions

  resources :fundstore_categories

  resources :holdings

  resources :stocks

  resources :user_accounts

  resources :user_holdings

  resources :user_transactions

end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
  belongs_to :user
end

app/models/fund.rb
class Fund < ActiveRecord::Base
  belongs_to :user_account
  belongs_to :fund_manager
  has_many :stocks
  has_many :fundstore_categories
  has_many :fund_managers
  has_many :user_transactions
  has_many :user_accounts
  has_many :fund_managements
  has_many :fund_transactions
  has_many :holdings
  has_many :user_holdings
  has_one :fund_cash
end

app/models/fund_cash.rb
class FundCash < ActiveRecord::Base
  belongs_to :fund
end

app/models/fund_management.rb
class FundManagement < ActiveRecord::Base
  belongs_to :fund_manager
  belongs_to :fund
end

app/models/fund_manager.rb
class FundManager < ActiveRecord::Base
  has_many :fund_managements
  has_many :funds
  validates_formatting_of :manager_email, using: :email
end

app/models/fund_store.rb
class FundStore < ActiveRecord::Base
end

app/models/fund_transaction.rb
class FundTransaction < ActiveRecord::Base
  belongs_to :stock
  belongs_to :fund
end

app/models/fundstore_category.rb
class FundstoreCategory < ActiveRecord::Base
  belongs_to :fund_store
  belongs_to :fund
  has_many :fund_categorizations
  has_many :funds
end

app/models/holding.rb
class Holding < ActiveRecord::Base
  belongs_to :stock
  belongs_to :fund
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :fund
  has_many :fund_transactions
  has_many :funds
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bank_accounts
  has_many :user_accounts
  validates_formatting_of :email, using: :email
end

app/models/user_account.rb
class UserAccount < ActiveRecord::Base
  belongs_to :user
  belongs_to :fund
  has_many :user_transactions
  has_many :funds
  has_many :user_holdings
end

app/models/user_holding.rb
class UserHolding < ActiveRecord::Base
  belongs_to :user_account
  belongs_to :fund
end

app/models/user_transaction.rb
class UserTransaction < ActiveRecord::Base
  belongs_to :user_account
  belongs_to :fund
end

app/controllers/fund_managers_controller.rb
class FundManagersController < ApplicationController
  before_action :set_fund_manager, only: [:show, :edit, :update, :destroy]

  # GET /fund_managers
  # GET /fund_managers.json
  def index
    @fund_managers = FundManager.all
  end

  # GET /fund_managers/1
  # GET /fund_managers/1.json
  def show
  end

  # GET /fund_managers/new
  def new
    @fund_manager = FundManager.new
  end

  # GET /fund_managers/1/edit
  def edit
  end

  # POST /fund_managers
  # POST /fund_managers.json
  def create
    @fund_manager = FundManager.new(fund_manager_params)

    respond_to do |format|
      if @fund_manager.save
        format.html { redirect_to @fund_manager, notice: 'Fund manager was successfully created.' }
        format.json { render :show, status: :created, location: @fund_manager }
      else
        format.html { render :new }
        format.json { render json: @fund_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fund_managers/1
  # PATCH/PUT /fund_managers/1.json
  def update
    respond_to do |format|
      if @fund_manager.update(fund_manager_params)
        format.html { redirect_to @fund_manager, notice: 'Fund manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @fund_manager }
      else
        format.html { render :edit }
        format.json { render json: @fund_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fund_managers/1
  # DELETE /fund_managers/1.json
  def destroy
    @fund_manager.destroy
    respond_to do |format|
      format.html { redirect_to fund_managers_url, notice: 'Fund manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fund_manager
      @fund_manager = FundManager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fund_manager_params
      params.require(:fund_manager).permit(:first_name, :last_name, :manager_email, :about, :manager_facebook, :manager_instagram, :manager_location, :manager_school, :manager_twitter, :manager_years_experience)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fund_cashes_helper.rb
module FundCashesHelper
end

app/helpers/fund_managers_helper.rb
module FundManagersHelper
end

app/helpers/fund_stores_helper.rb
module FundStoresHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/holdings_helper.rb
module HoldingsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fund_managers/_form.html.erb
<%= form_for @fund_manager, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :first_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :first_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :last_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :manager_email, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.email_field :manager_email, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :about, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :about, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :manager_facebook, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :manager_facebook, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :manager_instagram, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :manager_instagram, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :manager_location, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :manager_location, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :manager_school, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :manager_school, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :manager_twitter, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :manager_twitter, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :manager_years_experience, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :manager_years_experience, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  fund_managers_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/fund_managers/edit.html.erb
<%- model_class = FundManager -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => FundManager %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fund_managers/index.html.erb
<%- model_class = FundManager -%>
<div class="page-header">
  <h1><%=t '.title', :default => FundManager %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:manager_email) %></th>
      <th><%= model_class.human_attribute_name(:about) %></th>
      <th><%= model_class.human_attribute_name(:manager_facebook) %></th>
      <th><%= model_class.human_attribute_name(:manager_instagram) %></th>
      <th><%= model_class.human_attribute_name(:manager_location) %></th>
      <th><%= model_class.human_attribute_name(:manager_school) %></th>
      <th><%= model_class.human_attribute_name(:manager_twitter) %></th>
      <th><%= model_class.human_attribute_name(:manager_years_experience) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @fund_managers.each do |fund_manager| %>
      <tr>
        <td><%= fund_manager.id %></td>
        <td><%= fund_manager.first_name %></td>
        <td><%= fund_manager.last_name %></td>
        <td><%= fund_manager.manager_email %></td>
        <td><%= fund_manager.about %></td>
        <td><%= fund_manager.manager_facebook %></td>
        <td><%= fund_manager.manager_instagram %></td>
        <td><%= fund_manager.manager_location %></td>
        <td><%= fund_manager.manager_school %></td>
        <td><%= fund_manager.manager_twitter %></td>
        <td><%= fund_manager.manager_years_experience %></td>
        <td><%=l fund_manager.created_at, format: :long %></td>
        <td>
          <%= link_to fund_manager_path(fund_manager), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to fund_manager_path(fund_manager), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_fund_manager_path,
            :class => 'btn btn-primary' %>

app/views/fund_managers/new.html.erb
<%- model_class = FundManager -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => FundManager %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fund_managers/show.html.erb
<%- model_class = FundManager -%>
<div class="page-header">
  <h1><%=t '.title', :default => FundManager %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:first_name) %></dt>
      <dd><pre class="prettyprint"><%= @fund_manager.first_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:last_name) %></dt>
      <dd><pre class="prettyprint"><%= @fund_manager.last_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:manager_email) %></dt>
      <dd><pre class="prettyprint"><%= @fund_manager.manager_email %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:about) %></dt>
      <dd><pre class="prettyprint"><%= @fund_manager.about %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:manager_facebook) %></dt>
      <dd><pre class="prettyprint"><%= @fund_manager.manager_facebook %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:manager_instagram) %></dt>
      <dd><pre class="prettyprint"><%= @fund_manager.manager_instagram %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:manager_location) %></dt>
      <dd><pre class="prettyprint"><%= @fund_manager.manager_location %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:manager_school) %></dt>
      <dd><pre class="prettyprint"><%= @fund_manager.manager_school %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:manager_twitter) %></dt>
      <dd><pre class="prettyprint"><%= @fund_manager.manager_twitter %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:manager_years_experience) %></dt>
      <dd><pre class="prettyprint"><%= @fund_manager.manager_years_experience %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              fund_managers_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_fund_manager_path(@fund_manager), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              fund_manager_path(@fund_manager),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>